-- Selection and Display Callbacks Script File
-- Created:  March 18 2000
-- Modified: August 2 2000 8:24pm
-- Author:   Frank DeLise
--
-- 3D Studio Max Release 4.0

--***********************************************************************************************
-- MODIFY THIS AT YOUR OWN RISK
--***********************************************************************************************

-- Register Bone Objects
-- Uses Filters.Is_Bone Node functions defined in FilterFunctions.ms

--RegisterSelectFilterCallback Filters.Is_Bone "Bone"
--RegisterDisplayFilterCallback Filters.Is_Bone "Bone"

-- Register IK Goals
-- Uses Filters.Is_IKChain Node functions defined in FilterFunctions.ms

--RegisterSelectFilterCallback Filters.Is_IKChain "IK Chain"
--RegisterDisplayFilterCallback Filters.Is_IKChain "IK Chain"

-- Register Point Helpers
-- Uses Filters.Is_Point Node functions defined in FilterFunctions.ms

--RegisterSelectFilterCallback Filters.Is_Point "Point"
--RegisterDisplayFilterCallback Filters.Is_Point "Point"



